'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
const { chromium } = require('playwright');
const SRC=path.resolve(process.argv[2]||'clav-fix'); const WWW=path.resolve('www_shots'); const PORT=8769; const BASE=`http://127.0.0.1:${PORT}`;
const WEB_URL='https://script.google.com/macros/s/MOCK_DEPLOY/exec';
const FAIXAS=JSON.parse(fs.readFileSync('faixas.json','utf8'));
const VERSION=(fs.readFileSync(path.join(SRC,'00_Config.gs'),'utf8').match(/VERSION:\s*'([^']+)'/)||[])[1];
fs.rmSync(WWW,{recursive:true,force:true}); fs.mkdirSync(WWW,{recursive:true}); fs.copyFileSync(path.join(SRC,'Index.html'),path.join(WWW,'Index.html'));
const server=http.createServer((req,res)=>{ const file=path.join(WWW,decodeURIComponent(req.url.split('?')[0].replace(/^\//,'')||'Index.html')); if(!file.startsWith(WWW)||!fs.existsSync(file)){res.writeHead(404);res.end();return;} res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); res.end(fs.readFileSync(file)); });
const MOCK=require('./mock.js')({VERSION,WEB_URL,FAIXAS});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  await new Promise(r=>server.listen(PORT,'127.0.0.1',r));
  const browser=await chromium.launch();
  const ctx=await browser.newContext({viewport:{width:1400,height:900}}); const page=await ctx.newPage();
  page.on('pageerror',e=>console.log('PAGEERROR',e.message));
  await page.route('**/*',route=>{ const u=route.request().url(); if(u.startsWith(BASE)) return route.continue(); return route.abort(); });
  await page.addInitScript(MOCK);
  await page.goto(BASE+'/Index.html',{waitUntil:'load'});
  await page.waitForFunction(()=>window.__CLAV_CLIENT_READY__===true,null,{timeout:20000});
  await page.waitForFunction(()=>{const b=document.getElementById('loginBtn');return b&&!b.disabled;},null,{timeout:20000});
  await page.fill('#loginUser','denis'); await page.fill('#loginPass','Senha!12345'); await page.click('#loginBtn');
  await page.waitForFunction(()=>typeof STATE!=='undefined'&&STATE.user&&STATE.user.usuario==='denis',null,{timeout:20000});
  await page.evaluate(async()=>{ await abrirRegistro('ATD-1'); });
  await sleep(600);
  await page.screenshot({path:'shots/v1910/01-visao.png'});
  await page.evaluate(()=>showSection('preop')); await sleep(600);
  await page.screenshot({path:'shots/v1910/02-preop-topo.png'});
  const shot=async(sel,file)=>{ const el=await page.$(sel); if(el){ await el.scrollIntoViewIfNeeded(); await sleep(250); await el.screenshot({path:'shots/v1910/'+file}); } else console.log('sem',sel); };
  await shot('#reproBox','03-beta-hcg.png');
  await shot('#sb-capacidade-funcional-em-mets','04-capacidade-funcional.png');
  await shot('#alergiasChecks','05-alergias.png');
  await shot('#sb-estratificacao-final','06-estratificacao.png');
  await shot('#sb-conclusao-e-anestesia-proposta','07-conclusao.png');
  await page.evaluate(()=>{ const el=document.querySelector('#examGrid'); if(el) el.scrollIntoView(); }); await sleep(200);
  await page.evaluate(()=>showSection('triagem')); await sleep(400);
  await shot('#examGrid','08-exames.png');
  await page.evaluate(()=>showSection('calculadora')); await sleep(500);
  await page.screenshot({path:'shots/v1910/09-calculadora.png'});
  // modal de ciência e modal de conflito
  await page.evaluate(()=>{ showSection('preop'); const s=document.getElementById('conclusao'); ensureSelectValue(s,'Apto'); s.value='Apto'; s.dispatchEvent(new Event('change',{bubbles:true})); });
  await sleep(300);
  await page.click('#closeCaseBtn');
  await page.waitForFunction(()=>!document.getElementById('alertAckModal').classList.contains('hide'),null,{timeout:15000}).catch(()=>{});
  await sleep(300); await page.screenshot({path:'shots/v1910/10-ciencia-num-clique.png'});
  await page.evaluate(()=>closeAckModal());
  await page.evaluate(()=>abrirModalConflito('encerrar',{message:'O atendimento recebeu outra versão. Reabra e confira antes de mudar sua situação.'}));
  await sleep(300); await page.screenshot({path:'shots/v1910/11-conflito-escolha.png'});
  await page.evaluate(()=>fecharModalConflito());
  // folha impressa (HTML do navegador) com bordas arredondadas
  const html=await page.evaluate(()=>{ const d=calcularTudo().data; return '<!doctype html><html><head><meta charset="utf-8"><style>'+PRINT_SHEET_CSS+'</style></head><body>'+buildPreviewHtml(d,'AVALIACAO_PRE_ANESTESICA')+'</body></html>'; });
  fs.writeFileSync(path.join(WWW,'folha.html'),html);
  const p2=await ctx.newPage(); await p2.route('**/*',route=>{ const u=route.request().url(); if(u.startsWith(BASE)) return route.continue(); return route.abort(); });
  await p2.setViewportSize({width:900,height:1200}); await p2.goto(BASE+'/folha.html',{waitUntil:'load'}); await sleep(300);
  await p2.screenshot({path:'shots/v1910/12-folha-navegador.png',fullPage:false});
  console.log('capturas geradas');
  await browser.close(); server.close();
})();
