module.exports = ({ VERSION, WEB_URL, FAIXAS }) => `
(function(){
  const VERSION = ${JSON.stringify(VERSION)};
  const WEB_URL = ${JSON.stringify(WEB_URL)};
  const FAIXAS = ${JSON.stringify(FAIXAS)};
  const clone = o => JSON.parse(JSON.stringify(o === undefined ? null : o));
  const iso = () => new Date().toISOString();
  const hoje = () => { const d = new Date(); const p = n => String(n).padStart(2, '0'); return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate()); };
  function mergeDeep(t, s) { t = t || {}; Object.keys(s || {}).forEach(k => { if (s[k] && typeof s[k] === 'object' && !Array.isArray(s[k])) { if (!t[k] || typeof t[k] !== 'object' || Array.isArray(t[k])) t[k] = {}; mergeDeep(t[k], s[k]); } else t[k] = s[k]; }); return t; }
  const USER = { usuario_id: 'U1', usuario: 'denis', nome: 'Denis Paim Cipriani', perfil: 'ANESTESISTA', crm: '12345', rqe: '', email: 'denis@exemplo.com', telefone: '51999990000', ativo: 'SIM', senha: 'Senha!12345' };
  const publicUser = () => ({ usuario_id: USER.usuario_id, usuario: USER.usuario, nome: USER.nome, perfil: USER.perfil, crm: USER.crm, rqe: '', email: USER.email, telefone: USER.telefone,
    permissoes: { medical: true, save: true, openSpreadsheet: false, deleteRecords: false, manageUsers: false, closeCases: true, reopenCases: true, systemAnalysis: false, editAuditHistory: false } });
  const DB = { sessions: { 'TOKEN-DENIS-0123456789ABCDEF0123456789': 'U1' }, calls: [], atendimentos: {} };
  DB.atendimentos['ATD-1'] = { revision: 1, locked: false, payload: {
    paciente: { paciente_id: 'PAC-1', nome: 'Maria da Silva', nome_preferido: '', prontuario: 'CLAV-00012', nascimento: '1970-05-03', idade: '56', sexo: 'Feminino', cpf: '12345678901', telefone: '', cidade: 'Vacaria' },
    atendimento: { atendimento_id: 'ATD-1', paciente_id: 'PAC-1', status: 'ABERTO', revision: 1, data_consulta: hoje() + 'T09:00', data_cirurgia: hoje(), convenio: 'SUS', local: 'Hospital', updated_at: iso(), created_at: iso() },
    procedimento: { nome: 'Colecistectomia videolaparoscópica', lateralidade: 'Não se aplica', carater: 'Eletivo', data_cirurgia: hoje(), cirurgiao: 'Dr. Cirurgião', cirurgiao_1: 'Dr. Cirurgião' },
    triagem: { pa: '180/80', fc: '72', fr: '16', spo2: '98', temperatura: '36,5', peso: '70', altura: '170', responsavel: 'Liamara Berteli' },
    preop: { asa: 'ASA II', anestesiologista: 'Denis Paim Cipriani', data_avaliacao: hoje() + 'T10:00' },
    anamnese: { alergias: 'Dipirona', alergias_itens: ['Dipirona'] },
    conduta: { anestesia_proposta: 'Anestesia geral', medicacoes_internacao: [] },
    exames: {}, sistemas: {}, viaAerea: { mallampati: 'II' }, riscos: {}, seguranca: {}, srpa: {}, documentos: {}, calculos: {}, intraop: {}
  } };
  function row(id) { const a = DB.atendimentos[id]; const p = a.payload; return { atendimento_id: id, paciente_id: p.paciente.paciente_id, paciente_nome: p.paciente.nome, data_consulta: p.atendimento.data_consulta, data_cirurgia: p.atendimento.data_cirurgia, status: p.atendimento.status, procedimento: p.procedimento.nome, lateralidade: p.procedimento.lateralidade, carater: p.procedimento.carater, tipo_cirurgia: '', convenio: p.atendimento.convenio, local_procedimento: p.atendimento.local, cirurgiao: p.procedimento.cirurgiao, anestesiologista: p.preop.anestesiologista, triagem_concluida_em: '', conclusao: '', data_avaliacao: '', triagem_responsavel: p.triagem.responsavel, locked: a.locked ? 'SIM' : 'NAO', updated_at: p.atendimento.updated_at, revision: a.revision, alertas_count: 1, alertas_danger: 1 }; }
  const app = () => ({ nome: 'CLAV | Sistema Perioperatório', appName: 'CLAV | Sistema Perioperatório', shortName: 'CLAV', versao: VERSION, version: VERSION, schemaVersion: '8', logoUrl: '', salvamentoPlanilha: 'MANUAL_ONLY', spreadsheetSaveMode: 'MANUAL_ONLY', rascunhoLocalSegundos: 30, localAutosaveSeconds: 30, planilhaUrl: '', webAppUrl: WEB_URL, installed: true, installationMessage: '', now: iso(), iframeAllowed: true, faixasSv: FAIXAS });
  const LOOKUPS = { profissionais: [{ nome: 'Dr. Cirurgião', grupo: 'Cirurgia geral' }], anestesiologistas: ['Denis Paim Cipriani'], equipe_por_grupo: { 'Cirurgia geral': ['Dr. Cirurgião'], 'Anestesiologia': ['Denis Paim Cipriani'] }, procedimentos: ['Colecistectomia videolaparoscópica'], procedimentos_catalogo: [{ nome: 'Colecistectomia videolaparoscópica', grupo: 'Cirurgia geral', lateralidade: 'NA', carater: 'Eletivo', porte: '' }], convenios: ['SUS'], convenios_catalogo: [{ nome: 'SUS', grupo: '' }], medicacoes_catalogo: [{ nome: 'Dipirona', grupo: 'Analgésicos' }], municipios_rs: ['Vacaria'], lateralidade: ['Direita', 'Esquerda', 'Bilateral', 'Não se aplica'], carater: ['Eletivo', 'Urgência', 'Emergência'], tipo_cirurgia: ['Limpa', 'Potencialmente contaminada'], tecnicas: ['Anestesia geral', 'Raquianestesia'], locais: ['Hospital'], nome_instituicao: 'Clínica de Anestesiologia de Vacaria', cidade_instituicao: 'Vacaria/RS', logo_url: '' };
  const err = (code, message) => ({ ok: false, message, error: { code, origin: 'mock', traceId: 'ERR-mock' } });
  const ok = data => ({ ok: true, data: clone(data) });
  function sessao(token) { return DB.sessions[String(token || '')] ? USER : null; }
  function contexto(id) { const p = DB.atendimentos[id].payload; return { atendimento_id: id, status: p.atendimento.status, instituicao: 'Clínica de Anestesiologia de Vacaria', cidade_instituicao: 'Vacaria/RS',
    paciente: { paciente_id: p.paciente.paciente_id, nome: p.paciente.nome, nome_preferido: '', prontuario: p.paciente.prontuario, nascimento: p.paciente.nascimento, idade: p.paciente.idade, idade_formatada: p.paciente.idade + ' anos', sexo: p.paciente.sexo, potencial_gestacional: '', cidade: p.paciente.cidade, contexto_cuidado: '' },
    medidas: { peso: p.triagem.peso, altura: p.triagem.altura, imc: '24.2', imc_classe: 'Eutrofia', superficie_corporal: '1.81', clearance: '' },
    procedimento: { nome: p.procedimento.nome, lateralidade: p.procedimento.lateralidade, carater: p.procedimento.carater, porte: '', tipo_cirurgia: '', risco_cirurgico: '', data_cirurgia: p.procedimento.data_cirurgia, local: p.atendimento.local, convenio: p.atendimento.convenio, equipe: ['Dr. Cirurgião'], cirurgiao: 'Dr. Cirurgião' },
    preAnestesico: { asa: p.preop.asa, mets: '', estratificacao: '', anestesiologista: p.preop.anestesiologista, data_avaliacao: p.preop.data_avaliacao, conclusao: '', tecnica_proposta: p.conduta.anestesia_proposta, jejum: '', alergias: p.anamnese.alergias, alergias_itens: p.anamnese.alergias_itens, medicacoes_uso: '', historia_anestesica: '', compl_anestesicas_pessoais: [], compl_anestesicas_familiares: [], antecedentes: '', comorbidades: [], glp1: '' },
    viaAerea: { mallampati: 'II', abertura_oral: '', distancia_tireomentoniana: '', mobilidade_cervical: '', protrusao_mandibular: '', circunferencia_cervical: '', denticao: '', denticao_itens: [], observacoes: '', dificil_previsto: [] },
    riscos: { rcri: '', stop_bang: '', apfel: '', caprini: '', clav_score: '' }, basal: { pa: p.triagem.pa, fc: p.triagem.fc, fr: p.triagem.fr, spo2: p.triagem.spo2, temperatura: p.triagem.temperatura, glicemia: '', dor: '', responsavel: p.triagem.responsavel, registrado_em: '' },
    seguranca: { beta_hcg_status: '', beta_hcg_observacao: '', dum: '', protecao_menor_ativa: false, protecao_menor_pendente: false }, prescricaoPrevia: [], alertas: [{ id: 'SV_PAS_CRITICO', tipo: 'danger', texto: 'Sinal vital fora da faixa: PAS 180 mmHg', categoria: 'SINAIS_VITAIS' }],
    responsavelSala: { nome: USER.nome, crm: USER.crm, rqe: '', perfil: USER.perfil } }; }
  const API = {
    inicializar(token) { const u = sessao(token); return ok({ setupRequired: false, app: app(), usuario: u ? publicUser() : null, usuarios: u ? [publicUser()] : [], dashboard: { counts: { total: 1, abertos: 1, triagem: 0, pendentes: 0, encerrados: 0, hoje: 1, alertasCriticos: 1 }, generatedAt: iso() }, registros: u ? [row('ATD-1')] : [], lookups: u ? LOOKUPS : {}, sessionInvalid: !!token && !u, sessionToken: '', serverVersion: VERSION, schemaVersion: '8' }); },
    validarLogin(usuario, senha) { if (!usuario || !senha) return err('CREDENCIAIS_AUSENTES', 'Informe telefone, e-mail ou usuário e a senha.'); if (String(usuario).trim() !== USER.usuario && String(usuario).trim() !== USER.telefone && String(usuario).trim() !== USER.email) return err('CREDENCIAIS_INVALIDAS', 'Credenciais inválidas. Confira o telefone/e-mail e a senha.'); if (senha !== USER.senha) return err('CREDENCIAIS_INVALIDAS', 'Credenciais inválidas. A senha diferencia letras maiúsculas e minúsculas.'); const token = 'TOKEN-' + Math.random().toString(36).slice(2); DB.sessions[token] = 'U1'; return ok({ token, app: app(), usuario: publicUser(), usuarios: [publicUser()], dashboard: { counts: {}, generatedAt: iso() }, registros: [row('ATD-1')], lookups: LOOKUPS, planilhaUrl: '', serverVersion: VERSION, schemaVersion: '8' }); },
    encerrarSessao(token) { delete DB.sessions[token]; return ok({ encerrada: true }); },
    listarAtendimentos(f, token) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); return ok({ registros: [row('ATD-1')], dashboard: { counts: {}, generatedAt: iso() } }); },
    listarAgenda(data, token) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); return ok({ data: data || hoje(), registros: [row('ATD-1')] }); },
    listarMunicipios(token) { return ok({ municipios: [{ nome: 'Vacaria', uf: 'RS' }], total: 1 }); },
    buscarPacientes() { return ok({ resultados: [], total: 0 }); },
    historicoPaciente() { return ok({ registros: [] }); },
    verificarDuplicidadePaciente() { return ok({ duplicados: [] }); },
    relatorioAtendimentos() { return ok({ linhas: [], total: 0 }); },
    obterAtendimento(id, token) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); const a = DB.atendimentos[id]; if (!a) return err('NAO_ENCONTRADO', 'Atendimento não encontrado.'); const p = clone(a.payload); p.atendimento.revision = a.revision; return ok({ atendimento: p, locked: a.locked, alertas: [], revision: a.revision }); },
    salvarAtendimento(payload, token, meta) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); const id = payload && payload.atendimento && payload.atendimento.atendimento_id; const a = id ? DB.atendimentos[id] : null; if (!a) return err('NAO_ENCONTRADO', 'Atendimento inexistente ou excluído. A gravação não pode recriá-lo.'); if (a.locked) return err('ATENDIMENTO_BLOQUEADO', 'Este atendimento está encerrado. Reabra-o antes de alterar e salvar.'); if (Number(meta && meta.baseRevision) !== a.revision) return err('CONFLITO_REVISAO', 'Este atendimento foi alterado em outra aba ou por outro usuário. Reabra o registro antes de salvar.'); const merged = mergeDeep(clone(a.payload), clone(payload)); a.revision += 1; merged.atendimento.revision = a.revision; merged.atendimento.updated_at = iso(); merged.atendimento.paciente_id = merged.paciente.paciente_id; delete merged.atendimento._saveReceipt; a.payload = merged; return ok({ atendimento: merged, alertas: [], dashboard: { counts: {}, generatedAt: iso() }, registros: [row(id)], planilhaUrl: '', savedAt: iso(), revision: a.revision, requestId: meta.requestId, unchanged: false, verified: true, serverVersion: VERSION }); },
    intraopAbrirCaso(id, token) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); const a = DB.atendimentos[id]; if (!a) return err('NAO_ENCONTRADO', 'Atendimento não encontrado.'); return ok({ contexto: contexto(id), intraop: a.payload.intraop || {}, revision: a.revision, locked: a.locked, permissoes: publicUser().permissoes, usuario: publicUser(), podeSalvar: true, urlAbaPropria: '', installationId: WEB_URL }); },
    intraopSalvar(id, bloco, token, meta) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); const a = DB.atendimentos[id]; if (!a) return err('NAO_ENCONTRADO', 'Atendimento não encontrado.'); if (a.locked) return err('ATENDIMENTO_BLOQUEADO', 'Este atendimento está encerrado. Reabra-o antes de alterar e salvar.'); if (!meta || !meta.requestId || meta.baseRevision === undefined) return err('REVISAO_OBRIGATORIA', 'Atualize a ficha antes de salvar.'); if (Number(meta.baseRevision) !== a.revision) return err('CONFLITO_REVISAO', 'Este atendimento foi alterado em outra aba ou por outro usuário. Reabra o registro antes de salvar.'); a.payload.intraop = Object.assign({}, clone(bloco), { atualizado_em: meta.clientSavedAt, atualizado_por: 'denis' }); a.revision += 1; a.payload.atendimento.revision = a.revision; return ok({ atendimento: clone(a.payload), alertas: [], savedAt: iso(), revision: a.revision, requestId: meta.requestId, unchanged: false, verified: true, serverVersion: VERSION }); },
    intraopRegistrarAba(id, abaId, token) { if (!sessao(token)) return err('SESSION_INVALID', 'Sessão inválida. Faça login novamente.'); return ok({ registrada: true, limiteAtingido: false, maximo: 2, abertas: 1, outrasAbas: [], conflito: false }); },
    intraopLiberarAba() { return ok({ abertas: 0 }); },
    intraopFilaDoDia(dia, token) { if (!sessao(token)) return err('SESSION_EXPIRED', 'Sessão expirada. Faça login novamente.'); const r = row('ATD-1'); return ok({ data: dia, fila: [{ atendimento_id: 'ATD-1', paciente_nome: r.paciente_nome, prontuario: 'CLAV-00012', procedimento: r.procedimento, lateralidade: '', carater: r.carater, porte: '', local: r.local_procedimento, cirurgiao: r.cirurgiao, anestesiologista: r.anestesiologista, convenio: r.convenio, status: r.status, locked: '', alertas_danger: 1, beta_hcg_status: '', url: '' }], total: 1 }); }
  };
  const MOCKSRV = {
    DB, calls: DB.calls,
    call(fn, args) { DB.calls.push({ fn, args: clone(args) }); const h = API[fn]; if (!h) return err('NAO_SIMULADO', 'Função ' + fn + ' não simulada.'); return h.apply(null, args); },
    simulateFichaSave(id) { const a = DB.atendimentos[id]; a.payload.intraop = { ficha_v5_json: JSON.stringify({ versao: 'clav-ficha-v5', inicio: iso(), iniciado: true, obs: 'FICHA EM SALA', salvoEm: iso(), cab: {}, cfg: {}, series: [] }), ficha_v5_salvo_em: iso(), sinais: [{ horario: '10:05', col: 0, pa: '120/80', fc: '70' }], medicacoes: [], tecnica: 'Geral balanceada', anestesiologistas_responsaveis: 'Denis Paim Cipriani' }; a.revision += 1; a.payload.atendimento.revision = a.revision; return a.revision; },
    simulateIndexSave(id) { const a = DB.atendimentos[id]; a.payload.triagem.fc = '99'; a.revision += 1; a.payload.atendimento.revision = a.revision; return a.revision; },
    lock(id, v) { DB.atendimentos[id].locked = !!v; },
    revoke(token) { delete DB.sessions[token]; }
  };
  window.__MOCK_SERVER__ = MOCKSRV;
  window.__MOCK_HISTORY__ = [];
  window.__OPENED__ = [];
  function chain() { const h = { ok: null, fail: null }; const c = new Proxy({}, { get(_, prop) { if (prop === 'withSuccessHandler') return fn => { h.ok = fn; return c; }; if (prop === 'withFailureHandler') return fn => { h.fail = fn; return c; }; if (prop === 'withUserObject') return () => c; if (typeof prop !== 'string') return undefined; return (...args) => { setTimeout(() => { let res; try { res = MOCKSRV.call(prop, args); } catch (e) { if (h.fail) h.fail(e); return; } if (h.ok) h.ok(res); }, 8); }; } }); return c; }
  window.google = { script: {
    run: new Proxy({}, { get(_, prop) { return chain()[prop]; } }),
    url: { getLocation(cb) { setTimeout(() => cb({ hash: window.__MOCK_HASH__ || '', parameter: {}, parameters: {} }), 0); } },
    history: { replace(state, params, hash) { window.__MOCK_HISTORY__.push({ op: 'replace', params: params || null, hash: hash === undefined ? null : hash }); }, push(state, params, hash) { window.__MOCK_HISTORY__.push({ op: 'push', params, hash }); }, setChangeHandler() {} },
    host: { close() {}, setHeight() {}, setWidth() {}, origin: 'mock', editor: { focus() {} } }
  } };
  const realOpen = window.open; window.open = function (url, name) { window.__OPENED__.push({ url: String(url), name: String(name || '') }); return { focus() {}, closed: false, location: { href: url }, document: { write() {}, close() {} }, close() {} }; };
  void realOpen;
})();
`;
