'use strict';
const fs=require('fs'),path=require('path'),http=require('http');
const { chromium } = require('playwright');
const SRC=path.resolve(process.argv[2]||'clav-fix'); const WWW=path.resolve('www_shots2'); const PORT=8770; const BASE=`http://127.0.0.1:${PORT}`;
const WEB_URL='https://script.google.com/macros/s/MOCK_DEPLOY/exec';
const FAIXAS=JSON.parse(fs.readFileSync('faixas.json','utf8'));
const VERSION=(fs.readFileSync(path.join(SRC,'00_Config.gs'),'utf8').match(/VERSION:\s*'([^']+)'/)||[])[1];
fs.rmSync(WWW,{recursive:true,force:true}); fs.mkdirSync(WWW,{recursive:true}); fs.copyFileSync(path.join(SRC,'Index.html'),path.join(WWW,'Index.html'));
const server=http.createServer((req,res)=>{ const file=path.join(WWW,decodeURIComponent(req.url.split('?')[0].replace(/^\//,'')||'Index.html')); if(!file.startsWith(WWW)||!fs.existsSync(file)){res.writeHead(404);res.end();return;} res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); res.end(fs.readFileSync(file)); });
const MOCK=require('./mock.js')({VERSION,WEB_URL,FAIXAS});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  await new Promise(r=>server.listen(PORT,'127.0.0.1',r));
  const browser=await chromium.launch();
  const ctx=await browser.newContext({viewport:{width:1400,height:900}}); const page=await ctx.newPage();
  page.on('pageerror',e=>console.log('PAGEERROR',e.message));
  await page.route('**/*',route=>{ const u=route.request().url(); if(u.startsWith(BASE)) return route.continue(); return route.abort(); });
  await page.addInitScript(MOCK);
  await page.goto(BASE+'/Index.html',{waitUntil:'load'});
  await page.waitForFunction(()=>window.__CLAV_CLIENT_READY__===true,null,{timeout:20000});
  await page.waitForFunction(()=>{const b=document.getElementById('loginBtn');return b&&!b.disabled;},null,{timeout:20000});
  await page.fill('#loginUser','denis'); await page.fill('#loginPass','Senha!12345'); await page.click('#loginBtn');
  await page.waitForFunction(()=>typeof STATE!=='undefined'&&STATE.user&&STATE.user.usuario==='denis',null,{timeout:20000});
  await page.evaluate(async()=>{ await abrirRegistro('ATD-1'); showSection('preop'); });
  await sleep(600);
  const shot=async(sel,file)=>{ const el=await page.$(sel); if(el){ await el.scrollIntoViewIfNeeded(); await sleep(250); await el.screenshot({path:'shots/v1911/'+file}); } else console.log('sem',sel); };
  await page.evaluate(()=>{ const ta=document.querySelector('[data-sys-livre="cardio"]'); ta.value='Sopro sistólico conhecido, ecocardiograma 2025 normal'; ta.dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('[data-sys-item="HAS"]').click(); });
  await shot('#sb-exame-fisico','01-exame-fisico-com-dor-e-ausculta.png');
  await page.evaluate(()=>{ const el=document.getElementById('auscultaCardiacaTexto'); el.focus(); el.value='Sopro sistólico 2+/6 em foco mitral'; el.dispatchEvent(new Event('input',{bubbles:true})); el.dispatchEvent(new Event('blur',{bubbles:true})); });
  await shot('#sb-exame-fisico .ausc-field','02-ausculta-editada.png');
  await shot('#systemsReview .sys-block[data-sys="cardiovascular"]','03-revisao-cardio-duas-colunas.png');
  await shot('#systemsReview .sys-block[data-sys-block="outros"]','04-revisao-outros-gineco.png');
  await shot('#sb-via-aerea','05-via-aerea.png');
  await page.evaluate(()=>{ const marcar=v=>{ const cb=document.querySelector(`#consultRequestChecks input[value="${v}"]`); cb.checked=true; cb.dispatchEvent(new Event('change',{bubbles:true})); }; marcar('ECG'); marcar('Radiografia de tórax'); marcar('Avaliação cardiológica'); const inp=document.querySelector('#consultRequestDetails input[data-solicitacao-detalhe="ECG"]'); inp.value='Rotina pré-operatória (HAS, 56 anos)'; inp.dispatchEvent(new Event('input',{bubbles:true})); });
  await shot('[id^="sb-solicitacoes"]','06-solicitacoes-com-caixas.png');
  // folhas
  const mk=(tipo)=>page.evaluate((t)=>{ STATE.current=collectForm(); STATE.current.triagem.dor='3'; STATE.current.anamnese.medicacoes=''; fillForm(STATE.current); const d=calcularTudo().data; return '<!doctype html><html><head><meta charset="utf-8"><style>'+PRINT_SHEET_CSS+'</style></head><body>'+buildPreviewHtml(d,t)+'</body></html>'; }, tipo);
  fs.writeFileSync(path.join(WWW,'folha.html'), await mk('AVALIACAO_PRE_ANESTESICA'));
  fs.writeFileSync(path.join(WWW,'pedidos.html'), await mk('PEDIDOS'));
  const p2=await ctx.newPage(); await p2.route('**/*',route=>{ const u=route.request().url(); if(u.startsWith(BASE)) return route.continue(); return route.abort(); });
  await p2.setViewportSize({width:900,height:1250}); await p2.goto(BASE+'/folha.html',{waitUntil:'load'}); await sleep(300);
  await p2.screenshot({path:'shots/v1911/07-folha-pagina1.png',fullPage:false});
  await p2.evaluate(()=>{ const el=document.querySelectorAll('.pdf-section-title'); const alvo=Array.from(el).find(x=>/REVISÃO POR SISTEMAS/.test(x.textContent)); if(alvo) alvo.scrollIntoView(); }); await sleep(200);
  await p2.screenshot({path:'shots/v1911/08-folha-pagina2.png',fullPage:false});
  await p2.goto(BASE+'/pedidos.html',{waitUntil:'load'}); await sleep(300);
  await p2.screenshot({path:'shots/v1911/09-pedidos.png',fullPage:false});
  console.log('capturas geradas');
  await browser.close(); server.close();
})();
